# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"n\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfull_name\x18\x03 \x01(\t\x12\x14\n\x0cphone_number\x18\x04 \x01(\t\x12\r\n\x05\x65mail\x18\x05 \x01(\t\x12\x10\n\x08password\x18\x06 \x01(\t\"\x11\n\x0fGetUsersRequest\".\n\x10GetUsersResponse\x12\x1a\n\x05users\x18\x01 \x03(\x0b\x32\x0b.users.User\" \n\x12GetUserByIdRequest\x12\n\n\x02id\x18\x01 \x01(\t\"1\n\x13GetUserByIdResponse\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x11UpdateUserRequest\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User\"0\n\x12UpdateUserResponse\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x11\x44\x65leteUserRequest\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User\"0\n\x12\x44\x65leteUserResponse\x12\x1a\n\x05users\x18\x01 \x01(\x0b\x32\x0b.users.User\".\n\x11\x43reateUserRequest\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User\"/\n\x12\x43reateUserResponse\x12\x19\n\x04user\x18\x01 \x01(\x0b\x32\x0b.users.User2\xdd\x02\n\x05Users\x12=\n\x08GetUsers\x12\x16.users.GetUsersRequest\x1a\x17.users.GetUsersResponse\"\x00\x12\x46\n\x0bGetUserById\x12\x19.users.GetUserByIdRequest\x1a\x1a.users.GetUserByIdResponse\"\x00\x12\x43\n\nUpdateUser\x12\x18.users.UpdateUserRequest\x1a\x19.users.UpdateUserResponse\"\x00\x12\x43\n\nDeleteUser\x12\x18.users.DeleteUserRequest\x1a\x19.users.DeleteUserResponse\"\x00\x12\x43\n\nCreateUser\x12\x18.users.CreateUserRequest\x1a\x19.users.CreateUserResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=22
  _USER._serialized_end=132
  _GETUSERSREQUEST._serialized_start=134
  _GETUSERSREQUEST._serialized_end=151
  _GETUSERSRESPONSE._serialized_start=153
  _GETUSERSRESPONSE._serialized_end=199
  _GETUSERBYIDREQUEST._serialized_start=201
  _GETUSERBYIDREQUEST._serialized_end=233
  _GETUSERBYIDRESPONSE._serialized_start=235
  _GETUSERBYIDRESPONSE._serialized_end=284
  _UPDATEUSERREQUEST._serialized_start=286
  _UPDATEUSERREQUEST._serialized_end=333
  _UPDATEUSERRESPONSE._serialized_start=335
  _UPDATEUSERRESPONSE._serialized_end=383
  _DELETEUSERREQUEST._serialized_start=385
  _DELETEUSERREQUEST._serialized_end=432
  _DELETEUSERRESPONSE._serialized_start=434
  _DELETEUSERRESPONSE._serialized_end=482
  _CREATEUSERREQUEST._serialized_start=484
  _CREATEUSERREQUEST._serialized_end=530
  _CREATEUSERRESPONSE._serialized_start=532
  _CREATEUSERRESPONSE._serialized_end=579
  _USERS._serialized_start=582
  _USERS._serialized_end=931
# @@protoc_insertion_point(module_scope)
